spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8088
